spring:
  application:
    name: fraud-detection-service

account:
  service:
    url: http://localhost:8081

fraud:
  max-transactions-per-minute: 5
  suspicious-amount-multiplier: 5
  max-balance-percentage: 0.90